# Generated by Django 6.0.4 on 2026-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='напишите название книги')),
                ('description', models.TextField(blank=True, verbose_name='напишите описание книги')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите изображение книги')),
                ('book_file', models.FileField(upload_to='book/', verbose_name='загрузите файл книги')),
                ('type_book', models.CharField(choices=[('программирование', 'программирование'), ('наука', 'наука'), ('искусство', 'искусство')], default='программирование', max_length=100, verbose_name='выберите тип книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
