# Generated by Django 6.0.4 on 2026-04-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=100, verbose_name='укажите автора книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email автора или издательства'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='есть ли в наличии?'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='укажите цену книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='год издания'),
        ),
    ]
