# Generated by Django 6.0.4 on 2026-05-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя лошади')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя туриста')),
                ('Horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.horse', verbose_name='выбранная лошадь')),
            ],
        ),
    ]
