# Generated by Django 6.0.4 on 2026-05-04 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ошибка: оценка только от 1 до 5 (минимум 1)'), django.core.validators.MaxValueValidator(5, message='Ошибка: оценка только от 1 до 5 (максимум 5)')], verbose_name='Оценка')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.tourist', verbose_name='Турист')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='horse_tour.tourcompany', verbose_name='Тур компания')),
            ],
        ),
    ]
