# Generated by Django 6.0.4 on 2026-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='Horse',
            new_name='horse',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.ManyToManyField(related_name='services', to='horse_tour.tourcompany', verbose_name='Компания'),
        ),
    ]
